services:
  laravel-api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-api
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql-db

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-api

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-db
      PMA_USER: laravel
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - mysql-db

  react-frontend:
    image: node:20-alpine
    container_name: react-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"

volumes:
  db_data:
