apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: laravel-k8s
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: laravel
  MYSQL_USER: laravel
  MYSQL_PASSWORD: secret