apiVersion: batch/v1
kind: CronJob
metadata:
  name: laravel-scheduler
  namespace: laravel-k8s
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: scheduler
              image: laravel-api:local
              imagePullPolicy: Never
              command: ["php", "artisan", "schedule:run"]
              envFrom:
                - secretRef:
                    name: laravel-env
